//Name:       Elaine Pang, Taylor Tappe, Colin Zarzycki
//Date:       04/13/2012
//Assignment: EECS402 Project 5
//Purpose:    Enums

#ifndef _ENUMS_H_
#define _ENUMS_H_

//All cards (include suspects, weapons, rooms)
enum CardEnum{SCARLET_CARD, MUSTARD_CARD, WHITE_CARD, GREEN_CARD, PEACOCK_CARD,
    PLUM_CARD, KNIFE_CARD, CANDLESTICK_CARD, REVOLVER_CARD, ROPE_CARD,
    LEAD_PIPE_CARD, WRENCH_CARD, HALL_CARD, LOUNGE_CARD, DINING_ROOM_CARD,
    KITCHEN_CARD, BALLROOM_CARD, CONSERVATORY_CARD, BILLIARD_ROOM_CARD,
    LIBRARY_CARD, STUDY_CARD};

enum DifficultyEnum{VERY_EASY, EASY, MEDIUM, HARD, EXPERT};

enum SuspectEnum{SCARLET, MUSTARD, WHITE, GREEN, PEACOCK, PLUM,
    UNKNOWN_SUSPECT};

enum WeaponEnum{KNIFE, CANDLESTICK, REVOLVER, ROPE, LEAD_PIPE, WRENCH,
    UNKNOWN_WEAPON};

enum RoomEnum{HALL, LOUNGE, DINING_ROOM, KITCHEN, BALLROOM, CONSERVATORY,
    BILLIAR_ROOM, LIBRARY, STUDY, UNKNOWN_ROOM};

//Card types
enum CardTypeEnum{SUSPECT_CARD, WEAPON_CARD, ROOM_CARD};

//Tile types
enum TileTypeEnum{UNOCCUPIED_TILE, ROOM_TILE, OCCUPIED_TILE,
    OUT_OF_BOUNDS_TILE, VISITED_TILE};

//Directions
enum DirectionEnum{UP, DOWN, LEFT, RIGHT};

enum OrientationEnum{HORIZONTAL, VERTICAL};

enum ActionEnum{ACCUSE, SUGGEST, USE_SECRET_PASSAGE, ROLL, MOVE, END_TURN};

#endif
