#############################################################################
# Makefile for building: proj5Clue
# Generated by qmake (2.01a) (Qt 4.7.4) on: Thu Mar 29 18:01:11 2012
# Project:  proj5Clue.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile proj5Clue.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = BoardLocationClass.cpp \
		ClueMainWindowClass.cpp \
		DeckClass.cpp \
		main.cpp \
		PlayerClass.cpp moc_ClueMainWindowClass.cpp
OBJECTS       = BoardLocationClass.o \
		ClueMainWindowClass.o \
		DeckClass.o \
		main.o \
		PlayerClass.o \
		moc_ClueMainWindowClass.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		proj5Clue.pro
QMAKE_TARGET  = proj5Clue
DESTDIR       = 
TARGET        = proj5Clue

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_ClueMainWindowClass.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: proj5Clue.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile proj5Clue.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile proj5Clue.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/proj5Clue1.0.0 || $(MKDIR) .tmp/proj5Clue1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/proj5Clue1.0.0/ && $(COPY_FILE) --parents BoardLocationClass.h ClueMainWindowClass.h constants.h DeckClass.h PlayerClass.h .tmp/proj5Clue1.0.0/ && $(COPY_FILE) --parents BoardLocationClass.cpp ClueMainWindowClass.cpp DeckClass.cpp main.cpp PlayerClass.cpp .tmp/proj5Clue1.0.0/ && $(COPY_FILE) --parents ClueMainWindowClass.ui .tmp/proj5Clue1.0.0/ && (cd `dirname .tmp/proj5Clue1.0.0` && $(TAR) proj5Clue1.0.0.tar proj5Clue1.0.0 && $(COMPRESS) proj5Clue1.0.0.tar) && $(MOVE) `dirname .tmp/proj5Clue1.0.0`/proj5Clue1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/proj5Clue1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_ClueMainWindowClass.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_ClueMainWindowClass.cpp
moc_ClueMainWindowClass.cpp: ui_ClueMainWindowClass.h \
		constants.h \
		BoardLocationClass.h \
		PlayerClass.h \
		ClueMainWindowClass.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ClueMainWindowClass.h -o moc_ClueMainWindowClass.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_ClueMainWindowClass.h
compiler_uic_clean:
	-$(DEL_FILE) ui_ClueMainWindowClass.h
ui_ClueMainWindowClass.h: ClueMainWindowClass.ui
	/usr/bin/uic-qt4 ClueMainWindowClass.ui -o ui_ClueMainWindowClass.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

BoardLocationClass.o: BoardLocationClass.cpp BoardLocationClass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BoardLocationClass.o BoardLocationClass.cpp

ClueMainWindowClass.o: ClueMainWindowClass.cpp ClueMainWindowClass.h \
		ui_ClueMainWindowClass.h \
		constants.h \
		BoardLocationClass.h \
		PlayerClass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ClueMainWindowClass.o ClueMainWindowClass.cpp

DeckClass.o: DeckClass.cpp DeckClass.h \
		constants.h \
		BoardLocationClass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DeckClass.o DeckClass.cpp

main.o: main.cpp ClueMainWindowClass.h \
		ui_ClueMainWindowClass.h \
		constants.h \
		BoardLocationClass.h \
		PlayerClass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

PlayerClass.o: PlayerClass.cpp PlayerClass.h \
		constants.h \
		BoardLocationClass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PlayerClass.o PlayerClass.cpp

moc_ClueMainWindowClass.o: moc_ClueMainWindowClass.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ClueMainWindowClass.o moc_ClueMainWindowClass.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

